name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      FFMPEG_PLUGIN_KEYSTORE_PASSWORD: ${{ secrets.FFMPEG_PLUGIN_KEYSTORE_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Install dependencies
      run: sudo apt update && sudo apt install automake ant autopoint cmake build-essential libtool-bin pkg-config protobuf-compiler ragel subversion unzip git openjdk-11-jdk flex python3 wget nasm autogen patch
      
    - name: Set up Android environment
      run: |
        echo "ANDROID_SDK=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROID_NDK=$ANDROID_NDK_ROOT" >> $GITHUB_ENV

    - name: Clone and Build LibVLC
      run: |
        git clone https://code.videolan.org/videolan/vlc-android.git
        cd vlc-android
        buildsystem/compile.sh -l -a all -r
        cd ..

    - name: Copy LibVLC output to app
      run: |
        mkdir -p app/libs
        cp -r vlc-android/libvlc/build/outputs/aar/*.aar app/libs/

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Build FFmpeg and VLC-integrated APK
      run: |
        ./scripts/setup_environ.sh
        ./scripts/build_libs.sh
        ./gradlew assembleRelease
        ./gradlew bundleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk

    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: app-release-aab
        path: app/build/outputs/bundle/release/app-release.aab
